### Endpoint de teste
GET http://localhost:3003/ping

### Turma - Create Turma
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "turma0",
    "modulo": "0"
}

### Estudante Create Estudante
POST http://localhost:3003/estudante
Content-Type: application/json

{
    "nome":"testealuno1",
    "email":"testealuno3@gmail.com",
    "dataNascimento":"10/10/2010",
    "turmaId":"3a9d0dd3-96be-4603-9a2f-f64fd04b26da"
}

### Exercício 3 - Create product
GET http://localhost:3003/estudante/testealuno1


### Exercício 4 - Get products
GET http://localhost:3003/products

### Exercício 5 - Create purchase
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "103",
    "productId": "203",
    "quantity": 4
}

### Exercício 6 - Get user purchases
GET http://localhost:3003/users/103/purchases