### Endpoint de teste
GET http://localhost:3003/ping

### Turma - Create Turma
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "turma0",
    "modulo": "0"
}

### Exercício 2 - Get users
GET http://localhost:3003/users

### Exercício 3 - Create product
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Teste Product",
    "price": 500
}

### Exercício 4 - Get products
GET http://localhost:3003/products

### Exercício 5 - Create purchase
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "103",
    "productId": "203",
    "quantity": 4
}

### Exercício 6 - Get user purchases
GET http://localhost:3003/users/103/purchases


### Projeto docente
POST http://localhost:3003/criar-docente
Content-Type: application/json

{
    "nome":"Fulano",
    "email":"fulanbo@fulano.com",
    "data_nasc":"13/02/1990",
    "turma_id":"002"
}

### Buscar Docentes
GET http://localhost:3003/docentes

### Mudar Docente de Turma
POST http://localhost:3003/docente/

### 