### Endpoint de teste
GET http://localhost:3003/ping

### Turma - Create Turma
POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "turma0",
    "modulo": "0"
}

### Estudante Create Estudante
POST http://localhost:3003/estudante
Content-Type: application/json

{
    "nome":"testealuno1",
    "email":"testealuno3@gmail.com",
    "dataNascimento":"10/10/2010",
    "turmaId":"3a9d0dd3-96be-4603-9a2f-f64fd04b26da"
}

### Estudante - Edit product
PUT http://localhost:3003/estudante/editar-turma
Content-Type: application/json
{
    "email":"testealuno1",
    "newClass":"1fc667fc-f114-4e66-a422-110fa74b6c46"
}


### Exercício 4 - Get products
GET http://localhost:3003/products

### Exercício 5 - Create purchase
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "103",
    "productId": "203",
    "quantity": 4
}

### Exercício 6 - Get user purchases
GET http://localhost:3003/users/103/purchases


### Projeto docente
POST http://localhost:3003/criar-docente
Content-Type: application/json

{
    "nome":"Fulano",
    "email":"fulanbo@fulano.com",
    "data_nasc":"13/02/1990",
    "turma_id":"002"
}

### Buscar Docentes
GET http://localhost:3003/docentes

### Mudar Docente de Turma
POST http://localhost:3003/docente/

### 